//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Web_es_Ec {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Web_es_Ec() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Web_es_Ec", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Abono.
        /// </summary>
        internal static string Boton_Abonar {
            get {
                return ResourceManager.GetString("Boton_Abonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Boton_Aceptar {
            get {
                return ResourceManager.GetString("Boton_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Observaciones.
        /// </summary>
        internal static string Boton_Actualizar_Observacion {
            get {
                return ResourceManager.GetString("Boton_Actualizar_Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Abono.
        /// </summary>
        internal static string Boton_Agregar_Abono {
            get {
                return ResourceManager.GetString("Boton_Agregar_Abono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Agregar Prenda.
        /// </summary>
        internal static string Boton_Agregar_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Boton_Agregar_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anular Orden de Trabajo.
        /// </summary>
        internal static string Boton_Anular_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Boton_Anular_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda.
        /// </summary>
        internal static string Boton_Buscar {
            get {
                return ResourceManager.GetString("Boton_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda de Prendas .
        /// </summary>
        internal static string Boton_Buscar_Prendas {
            get {
                return ResourceManager.GetString("Boton_Buscar_Prendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Boton_Cancelar {
            get {
                return ResourceManager.GetString("Boton_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar la Orden de  Trabajo.
        /// </summary>
        internal static string Boton_Cerrar_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Boton_Cerrar_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cliente.
        /// </summary>
        internal static string Boton_Crear_Cliente {
            get {
                return ResourceManager.GetString("Boton_Crear_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear o Modiicar Cliente .
        /// </summary>
        internal static string Boton_Crear_Modificar_Cliente {
            get {
                return ResourceManager.GetString("Boton_Crear_Modificar_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Entrega/Recepción Prenda.
        /// </summary>
        internal static string Boton_Entrega_Recepcion_Prenda {
            get {
                return ResourceManager.GetString("Boton_Entrega_Recepcion_Prenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Orden de  Trabajo.
        /// </summary>
        internal static string Boton_Guardar_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Boton_Guardar_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso Sistema.
        /// </summary>
        internal static string Boton_Ingreso_Sistema {
            get {
                return ResourceManager.GetString("Boton_Ingreso_Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string Boton_Limpiar {
            get {
                return ResourceManager.GetString("Boton_Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Reporte.
        /// </summary>
        internal static string Btn_Generar_Reporte {
            get {
                return ResourceManager.GetString("Btn_Generar_Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido  Materno(*).
        /// </summary>
        internal static string Label_Apellido_Materno {
            get {
                return ResourceManager.GetString("Label_Apellido_Materno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno (*).
        /// </summary>
        internal static string Label_Apellido_Paterno {
            get {
                return ResourceManager.GetString("Label_Apellido_Paterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Label_Cabecera_Grid_Cantidad {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Label_Cabecera_Grid_Cliente {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de la Orden de  Trabajo.
        /// </summary>
        internal static string Label_Cabecera_Grid_Codigo_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Codigo_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        internal static string Label_Cabecera_Grid_Color {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta  Por Cobrar Id.
        /// </summary>
        internal static string Label_Cabecera_Grid_Cuenta_Por_Cobrar_Id {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Cuenta_Por_Cobrar_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Creación.
        /// </summary>
        internal static string Label_Cabecera_Grid_Fecha_Creacion {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Fecha_Creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Entrega Orden.
        /// </summary>
        internal static string Label_Cabecera_Grid_Fecha_Entrega {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Fecha_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Modificación.
        /// </summary>
        internal static string Label_Cabecera_Grid_Fecha_Modificacion {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Fecha_Modificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Recepción Orden.
        /// </summary>
        internal static string Label_Cabecera_Grid_Fecha_Recepcion {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Fecha_Recepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        internal static string Label_Cabecera_Grid_Marca {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material.
        /// </summary>
        internal static string Label_Cabecera_Grid_Material {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Observaciones.
        /// </summary>
        internal static string Label_Cabecera_Grid_Mostrar_Observaciones {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Mostrar_Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Factura.
        /// </summary>
        internal static string Label_Cabecera_Grid_Numero_Factura {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Numero_Factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de  Orden.
        /// </summary>
        internal static string Label_Cabecera_Grid_Numero_Orden {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Numero_Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Prendas.
        /// </summary>
        internal static string Label_Cabecera_Grid_Numero_Prendas {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Numero_Prendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prenda.
        /// </summary>
        internal static string Label_Cabecera_Grid_Prenda {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Prenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen Cobro.
        /// </summary>
        internal static string Label_Cabecera_Grid_Resumen_Cobro {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Resumen_Cobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saldo.
        /// </summary>
        internal static string Label_Cabecera_Grid_Saldo {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talla.
        /// </summary>
        internal static string Label_Cabecera_Grid_Talla {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Talla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        internal static string Label_Cabecera_Grid_Valor {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Total.
        /// </summary>
        internal static string Label_Cabecera_Grid_Valor_Total {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Valor_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Unitario.
        /// </summary>
        internal static string Label_Cabecera_Grid_Valor_Unitario {
            get {
                return ResourceManager.GetString("Label_Cabecera_Grid_Valor_Unitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Label_Cantidad {
            get {
                return ResourceManager.GetString("Label_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad (*).
        /// </summary>
        internal static string Label_Ciudad {
            get {
                return ResourceManager.GetString("Label_Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        internal static string Label_Color {
            get {
                return ResourceManager.GetString("Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasena (*).
        /// </summary>
        internal static string Label_Contrasena {
            get {
                return ResourceManager.GetString("Label_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dia de Entrega.
        /// </summary>
        internal static string Label_Dia_Entrega {
            get {
                return ResourceManager.GetString("Label_Dia_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección (*).
        /// </summary>
        internal static string Label_Direccion {
            get {
                return ResourceManager.GetString("Label_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección del Cliente.
        /// </summary>
        internal static string Label_Direccion_Cliente {
            get {
                return ResourceManager.GetString("Label_Direccion_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de Correo (*).
        /// </summary>
        internal static string Label_Direccion_Correo {
            get {
                return ResourceManager.GetString("Label_Direccion_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Pago.
        /// </summary>
        internal static string Label_Estado_Pago {
            get {
                return ResourceManager.GetString("Label_Estado_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etapa de Proceso.
        /// </summary>
        internal static string Label_Etapa_Proceso {
            get {
                return ResourceManager.GetString("Label_Etapa_Proceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etapa de Proceso Destino.
        /// </summary>
        internal static string Label_Etapa_Proceso_Destino {
            get {
                return ResourceManager.GetString("Label_Etapa_Proceso_Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Ingreso.
        /// </summary>
        internal static string Label_Fecha {
            get {
                return ResourceManager.GetString("Label_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Entrega.
        /// </summary>
        internal static string Label_Fecha_Entrega {
            get {
                return ResourceManager.GetString("Label_Fecha_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Entrega Efectiva.
        /// </summary>
        internal static string Label_Fecha_Entrega_Real {
            get {
                return ResourceManager.GetString("Label_Fecha_Entrega_Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Entrega Propuesta.
        /// </summary>
        internal static string Label_Fecha_Entrega_Registrada {
            get {
                return ResourceManager.GetString("Label_Fecha_Entrega_Registrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Orden de  Trabajo.
        /// </summary>
        internal static string Label_Fecha_Ingreso_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Label_Fecha_Ingreso_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento (*).
        /// </summary>
        internal static string Label_Fecha_Nacimiento {
            get {
                return ResourceManager.GetString("Label_Fecha_Nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genero (*).
        /// </summary>
        internal static string Label_Genero {
            get {
                return ResourceManager.GetString("Label_Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        internal static string Label_Marca {
            get {
                return ResourceManager.GetString("Label_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material .
        /// </summary>
        internal static string Label_Material {
            get {
                return ResourceManager.GetString("Label_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Cliente.
        /// </summary>
        internal static string Label_Nombre_Cliente {
            get {
                return ResourceManager.GetString("Label_Nombre_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Perfil .
        /// </summary>
        internal static string Label_Nombre_Perfil {
            get {
                return ResourceManager.GetString("Label_Nombre_Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Documento.
        /// </summary>
        internal static string Label_Numero_Documento {
            get {
                return ResourceManager.GetString("Label_Numero_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de  Orden.
        /// </summary>
        internal static string Label_Numero_Orden {
            get {
                return ResourceManager.GetString("Label_Numero_Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de Telefono (*).
        /// </summary>
        internal static string Label_Numero_Telefono {
            get {
                return ResourceManager.GetString("Label_Numero_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        internal static string Label_Observacion {
            get {
                return ResourceManager.GetString("Label_Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porque la anulación ?.
        /// </summary>
        internal static string Label_Observaciones_Anulacion {
            get {
                return ResourceManager.GetString("Label_Observaciones_Anulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais (*).
        /// </summary>
        internal static string Label_Pais {
            get {
                return ResourceManager.GetString("Label_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prenda.
        /// </summary>
        internal static string Label_Prenda {
            get {
                return ResourceManager.GetString("Label_Prenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Nombre (*).
        /// </summary>
        internal static string Label_Primer_Nombre {
            get {
                return ResourceManager.GetString("Label_Primer_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia (*).
        /// </summary>
        internal static string Label_Provincia {
            get {
                return ResourceManager.GetString("Label_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Nombre (*).
        /// </summary>
        internal static string Label_Segundo_Nombre {
            get {
                return ResourceManager.GetString("Label_Segundo_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucursal.
        /// </summary>
        internal static string Label_Sucursal {
            get {
                return ResourceManager.GetString("Label_Sucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talla.
        /// </summary>
        internal static string Label_Talla {
            get {
                return ResourceManager.GetString("Label_Talla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono de Cliente.
        /// </summary>
        internal static string Label_Telefono_Cliente {
            get {
                return ResourceManager.GetString("Label_Telefono_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Correo (*).
        /// </summary>
        internal static string Label_Tipo_Correo {
            get {
                return ResourceManager.GetString("Label_Tipo_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Direccion (*).
        /// </summary>
        internal static string Label_Tipo_Direccion {
            get {
                return ResourceManager.GetString("Label_Tipo_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Documento (*).
        /// </summary>
        internal static string Label_Tipo_Documento {
            get {
                return ResourceManager.GetString("Label_Tipo_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Lavado.
        /// </summary>
        internal static string Label_Tipo_Lavado {
            get {
                return ResourceManager.GetString("Label_Tipo_Lavado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Telefono (*).
        /// </summary>
        internal static string Label_Tipo_Telefono {
            get {
                return ResourceManager.GetString("Label_Tipo_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario (*).
        /// </summary>
        internal static string Label_Usuario {
            get {
                return ResourceManager.GetString("Label_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Label_Usuario_No_Obligatorio {
            get {
                return ResourceManager.GetString("Label_Usuario_No_Obligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor del Abono.
        /// </summary>
        internal static string Label_Valor_Abonar {
            get {
                return ResourceManager.GetString("Label_Valor_Abonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Total.
        /// </summary>
        internal static string Label_Valor_Total {
            get {
                return ResourceManager.GetString("Label_Valor_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Unitario.
        /// </summary>
        internal static string Label_Valor_Unitario {
            get {
                return ResourceManager.GetString("Label_Valor_Unitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Abono.
        /// </summary>
        internal static string Literal_Agregar_Abono {
            get {
                return ResourceManager.GetString("Literal_Agregar_Abono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anular Orden.
        /// </summary>
        internal static string Literal_Anular_Orden {
            get {
                return ResourceManager.GetString("Literal_Anular_Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar la Orden.
        /// </summary>
        internal static string Literal_Cerrar_Orden {
            get {
                return ResourceManager.GetString("Literal_Cerrar_Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Pago.
        /// </summary>
        internal static string Literal_Datos_Pago {
            get {
                return ResourceManager.GetString("Literal_Datos_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/mm/yyyy.
        /// </summary>
        internal static string Marca_Agua_Fecha {
            get {
                return ResourceManager.GetString("Marca_Agua_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente esta creado  ya no se puede ingresar  nuevamente el cliente.
        /// </summary>
        internal static string Mensaje_Cliente_Existe {
            get {
                return ResourceManager.GetString("Mensaje_Cliente_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente no existe  verifique   la información.
        /// </summary>
        internal static string Mensaje_Cliente_No_Existe {
            get {
                return ResourceManager.GetString("Mensaje_Cliente_No_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error contacte con el administrador.
        /// </summary>
        internal static string Mensaje_Error_Sistema {
            get {
                return ResourceManager.GetString("Mensaje_Error_Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación exitosa.
        /// </summary>
        internal static string Mensaje_Exitoso {
            get {
                return ResourceManager.GetString("Mensaje_Exitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe información.
        /// </summary>
        internal static string Mensaje_Informacion_No_existe {
            get {
                return ResourceManager.GetString("Mensaje_Informacion_No_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La orden de  trabajo no debe de  tener más de 20 prendas.
        /// </summary>
        internal static string Mensaje_Mayor_Veinte_Prendas {
            get {
                return ResourceManager.GetString("Mensaje_Mayor_Veinte_Prendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de orden existe, no puede ingresar.
        /// </summary>
        internal static string Mensaje_Numero_Orden_Existe {
            get {
                return ResourceManager.GetString("Mensaje_Numero_Orden_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dato Obligatorio.
        /// </summary>
        internal static string Mensaje_Obligatorio {
            get {
                return ResourceManager.GetString("Mensaje_Obligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La orden se encuentra cerrada  o anulada, la orden solo esta disponible como consulta.
        /// </summary>
        internal static string Mensaje_Orden_Cerrada {
            get {
                return ResourceManager.GetString("Mensaje_Orden_Cerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe información con esa  orden de trabajo.
        /// </summary>
        internal static string Mensaje_Orden_Trabajo_No_Existe {
            get {
                return ResourceManager.GetString("Mensaje_Orden_Trabajo_No_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje del Sistema.
        /// </summary>
        internal static string Mensaje_Sistema {
            get {
                return ResourceManager.GetString("Mensaje_Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de abono es mayor que el valor total, revise los valores.
        /// </summary>
        internal static string Mensaje_Valor_Abono_Mayo_PagoTotal {
            get {
                return ResourceManager.GetString("Mensaje_Valor_Abono_Mayo_PagoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda del Cliente Por  Numero de Identificación.
        /// </summary>
        internal static string Panel_Busqueda_Cliente {
            get {
                return ResourceManager.GetString("Panel_Busqueda_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda Orden de Trabajo.
        /// </summary>
        internal static string Panel_Busqueda_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Panel_Busqueda_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda por Fecha .
        /// </summary>
        internal static string Panel_Busqueda_Reporte_Diario_Fecha {
            get {
                return ResourceManager.GetString("Panel_Busqueda_Reporte_Diario_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda de  Cuentas  Por Cobrar.
        /// </summary>
        internal static string Panel_Cabecera_Cuenta_Por_Cobrar {
            get {
                return ResourceManager.GetString("Panel_Cabecera_Cuenta_Por_Cobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezado Orden de Trabajo.
        /// </summary>
        internal static string Panel_Cabecera_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Panel_Cabecera_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Domicilio Cliente.
        /// </summary>
        internal static string Panel_Datos_Domicilio_Cliente {
            get {
                return ResourceManager.GetString("Panel_Datos_Domicilio_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Generales Cliente.
        /// </summary>
        internal static string Panel_Datos_Generales_Cliente {
            get {
                return ResourceManager.GetString("Panel_Datos_Generales_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Telefono y Mail del Cliente.
        /// </summary>
        internal static string Panel_Datos_Telefono_Mail_Cliente {
            get {
                return ResourceManager.GetString("Panel_Datos_Telefono_Mail_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Orden de  Trabajo.
        /// </summary>
        internal static string Panel_Detalle_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Panel_Detalle_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese los accesos  para la recepción de la mercaderia.
        /// </summary>
        internal static string Panel_Entrega_Recepcion_Seguridad {
            get {
                return ResourceManager.GetString("Panel_Entrega_Recepcion_Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Pago.
        /// </summary>
        internal static string Panel_Forma_Pago {
            get {
                return ResourceManager.GetString("Panel_Forma_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial Pago.
        /// </summary>
        internal static string Panel_Historial_Pago {
            get {
                return ResourceManager.GetString("Panel_Historial_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial Proceso.
        /// </summary>
        internal static string Panel_Historial_Proceso {
            get {
                return ResourceManager.GetString("Panel_Historial_Proceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese Sus Credenciales de Acceso.
        /// </summary>
        internal static string Panel_Ingreso_Sistema {
            get {
                return ResourceManager.GetString("Panel_Ingreso_Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de  Prendas.
        /// </summary>
        internal static string Panel_Listado_Prenda {
            get {
                return ResourceManager.GetString("Panel_Listado_Prenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la Orden de  Trabajo.
        /// </summary>
        internal static string Panel_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Panel_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresión Orden.
        /// </summary>
        internal static string Titulo_Impresion_Orden {
            get {
                return ResourceManager.GetString("Titulo_Impresion_Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al Sistema de la Química.
        /// </summary>
        internal static string Titulo_Ingreso_Sistema {
            get {
                return ResourceManager.GetString("Titulo_Ingreso_Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        internal static string Titulo_Pagina_Cliente {
            get {
                return ResourceManager.GetString("Titulo_Pagina_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Orden de Trabajo.
        /// </summary>
        internal static string Titulo_Pagina_Consulta_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Titulo_Pagina_Consulta_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas Por Cobrar.
        /// </summary>
        internal static string Titulo_Pagina_Cuenta_Por_Cobrar {
            get {
                return ResourceManager.GetString("Titulo_Pagina_Cuenta_Por_Cobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrega/Recepción de Prendas.
        /// </summary>
        internal static string Titulo_Pagina_Entrega_Recepcion {
            get {
                return ResourceManager.GetString("Titulo_Pagina_Entrega_Recepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden de Trabajo.
        /// </summary>
        internal static string Titulo_Pagina_Orden_Trabajo {
            get {
                return ResourceManager.GetString("Titulo_Pagina_Orden_Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Entrega/Recepción de Prendas.
        /// </summary>
        internal static string Titulo_Pagina_Reporte_Entrega_Recepcion_Prendas {
            get {
                return ResourceManager.GetString("Titulo_Pagina_Reporte_Entrega_Recepcion_Prendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema Decisiones Inteligentes Desarrollado por Rodrigo Utreras y Jorge López.
        /// </summary>
        internal static string Titulo_Pie_Pagina_Sistema {
            get {
                return ResourceManager.GetString("Titulo_Pie_Pagina_Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Diario.
        /// </summary>
        internal static string Titulo_Reporte_Diario {
            get {
                return ResourceManager.GetString("Titulo_Reporte_Diario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decisiones Inteligentes.
        /// </summary>
        internal static string Titulo_Sistema {
            get {
                return ResourceManager.GetString("Titulo_Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/mm/yyyy.
        /// </summary>
        internal static string WaterMarke_Fecha {
            get {
                return ResourceManager.GetString("WaterMarke_Fecha", resourceCulture);
            }
        }
    }
}
