//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCESO()
        {
            this.ACCESO_PERFIL = new HashSet<ACCESO_PERFIL>();
        }
    
        public int ACCESO_ID { get; set; }
        public Nullable<int> MODULO_ID { get; set; }
        public Nullable<int> SUBMODULO_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string URL { get; set; }
        public Nullable<bool> ESTA_HABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESO_PERFIL> ACCESO_PERFIL { get; set; }
        public virtual MODULO MODULO { get; set; }
        public virtual SUBMODULO SUBMODULO { get; set; }
    }
}
