//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESO_PERFIL
    {
        public int ACCESO_PERFIL_ID { get; set; }
        public Nullable<int> ACCESO_ID { get; set; }
        public Nullable<int> PERFIL_ID { get; set; }
    
        public virtual ACCESO ACCESO { get; set; }
        public virtual PERFIL PERFIL { get; set; }
    }
}
