//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCION_REGLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCION_REGLA()
        {
            this.HISTORIAL_REGLA = new HashSet<HISTORIAL_REGLA>();
        }
    
        public int ACCION_REGLA_ID { get; set; }
        public Nullable<int> REGLA_ID { get; set; }
        public Nullable<int> PRODUCTO_ID { get; set; }
        public Nullable<bool> ESTA_HABILITADO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual REGLA REGLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_REGLA> HISTORIAL_REGLA { get; set; }
    }
}
