//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA_VISITA
    {
        public int AGENDA_VISITA_ID { get; set; }
        public Nullable<int> VISITA_ID { get; set; }
        public Nullable<int> DIA_ID { get; set; }
        public Nullable<int> CLIENTE_ID { get; set; }
        public Nullable<int> VENDEDOR_ID { get; set; }
    
        public virtual DIA DIA { get; set; }
        public virtual VISITA VISITA { get; set; }
    }
}
