//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARQUEO_CAJA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARQUEO_CAJA()
        {
            this.DETALLE_ARQUEO_CAJA = new HashSet<DETALLE_ARQUEO_CAJA>();
        }
    
        public int ARQUEO_CAJA_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.TimeSpan> HORA { get; set; }
        public Nullable<int> USUARIO_ADMINISTRADOR_ID { get; set; }
        public Nullable<int> USUARIO_DELEGADO_ID { get; set; }
        public Nullable<decimal> TOTAL_REPORTE { get; set; }
        public Nullable<decimal> TOTAL_PRESENTADO { get; set; }
        public Nullable<decimal> DIFERENCIA { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> NUMERO_VERSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ARQUEO_CAJA> DETALLE_ARQUEO_CAJA { get; set; }
    }
}
