//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABECERA_FACTURACION
    {
        public int CABECERA_FACTURACION_ID { get; set; }
        public Nullable<int> PUNTO_VENTA_ID { get; set; }
        public Nullable<int> SUCURSAL_ID { get; set; }
        public Nullable<int> LLEVA_CONTABILIDAD_ID { get; set; }
        public Nullable<int> TIPO_AMBIENTE_ID { get; set; }
        public Nullable<int> TIPO_EMISION_ID { get; set; }
        public Nullable<int> MONEDA_ID { get; set; }
    
        public virtual LLEVA_CONTABILIDAD LLEVA_CONTABILIDAD { get; set; }
        public virtual MONEDA MONEDA { get; set; }
        public virtual PUNTO_VENTA PUNTO_VENTA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual TIPO_AMBIENTE TIPO_AMBIENTE { get; set; }
        public virtual TIPO_EMISION TIPO_EMISION { get; set; }
    }
}
