//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABECERA_MOVIMIENTO_FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CABECERA_MOVIMIENTO_FACTURA()
        {
            this.DETALLE_MOVIMIENTO_FACTURA = new HashSet<DETALLE_MOVIMIENTO_FACTURA>();
        }
    
        public long CABECERA_MOVIMIENTO_FACTURA_ID { get; set; }
        public Nullable<long> CABECERA_MOVIMIENTO_TRIBUTARIO_ID { get; set; }
        public Nullable<System.DateTime> FECHA_EMISION { get; set; }
        public string DIRECCION { get; set; }
    
        public virtual CABECERA_MOVIMIENTO_TRIBUTARIO CABECERA_MOVIMIENTO_TRIBUTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_MOVIMIENTO_FACTURA> DETALLE_MOVIMIENTO_FACTURA { get; set; }
    }
}
