//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA_POR_PAGAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTA_POR_PAGAR()
        {
            this.HISTORIAL_CUENTA_POR_PAGAR = new HashSet<HISTORIAL_CUENTA_POR_PAGAR>();
        }
    
        public long CUENTA_POR_PAGAR_ID { get; set; }
        public Nullable<long> PROVEDOR_ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<int> USUARIO_CREACION_ID { get; set; }
        public Nullable<int> USUARIO_MODIFICACION_ID { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public Nullable<int> SUCURSAL_ID { get; set; }
        public Nullable<int> PUNTO_VENTA_ID { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public string NUMERO_ORDEN { get; set; }
        public Nullable<int> CIERRE_MES_ID { get; set; }
    
        public virtual CIERRE_MES CIERRE_MES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_CUENTA_POR_PAGAR> HISTORIAL_CUENTA_POR_PAGAR { get; set; }
    }
}
