//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA_POR_COBRAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTA_POR_COBRAR()
        {
            this.DETALLE_CUENTA_POR_COBRAR = new HashSet<DETALLE_CUENTA_POR_COBRAR>();
        }
    
        public long CUENTA_POR_COBRAR_ID { get; set; }
        public Nullable<long> INDIVIDUO_ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public Nullable<bool> ESTADO_CUENTA_POR_SUCURSAL { get; set; }
        public Nullable<int> SUCURSAL_ID { get; set; }
        public Nullable<int> PUNTO_VENTA_ID { get; set; }
        public Nullable<bool> ESTADO_CUENTA_POR_PUNTO_VENTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CUENTA_POR_COBRAR> DETALLE_CUENTA_POR_COBRAR { get; set; }
    }
}
