//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_VENTA_COMISION_INDUSTRIALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_VENTA_COMISION_INDUSTRIALES()
        {
            this.ORDEN_TRABAJO_COMISION = new HashSet<ORDEN_TRABAJO_COMISION>();
        }
    
        public int DETALLE_VENTA_COMISION_INDUSTRIALES_ID { get; set; }
        public Nullable<int> VENTA_COMISION_INDUSTRIALES_ID { get; set; }
        public Nullable<int> PRODUCTO_PRECIO_ID { get; set; }
        public Nullable<bool> ESTA_HABILITADO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
    
        public virtual PRODUCTO_PRECIO PRODUCTO_PRECIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual VENTA_COMISION_INDUSTRIALES VENTA_COMISION_INDUSTRIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_TRABAJO_COMISION> ORDEN_TRABAJO_COMISION { get; set; }
    }
}
