//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_HISTORIAL_REPROCESO
    {
        public int DETALLE_HISTORIAL_REPROCESO_ID { get; set; }
        public Nullable<long> HISTORIAL_REPROCESO_ID { get; set; }
        public Nullable<int> TIPO_REPROCESO_ID { get; set; }
        public string MOTIVO { get; set; }
    
        public virtual TIPO_REPROCESO TIPO_REPROCESO { get; set; }
        public virtual HISTORIAL_REPROCESO HISTORIAL_REPROCESO { get; set; }
    }
}
