//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ARQUEO_CAJA
    {
        public int DETALLE_ARQUEO_CAJA_ID { get; set; }
        public Nullable<int> ARQUEO_CAJA_ID { get; set; }
        public Nullable<long> VENTA_ID { get; set; }
        public Nullable<decimal> VALOR_TOTAL { get; set; }
        public Nullable<int> TIPO_OPERACION { get; set; }
    
        public virtual ARQUEO_CAJA ARQUEO_CAJA { get; set; }
    }
}
