//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        public int DIRECCION_ID { get; set; }
        public Nullable<int> PAIS_ID { get; set; }
        public Nullable<int> ESTADO_ID { get; set; }
        public Nullable<int> CIUDAD_ID { get; set; }
        public Nullable<int> INDIVIDUO_ID { get; set; }
        public Nullable<int> TIPO_DIRECCION_ID { get; set; }
        public string DESCRIPCION_DIRECCION { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual PAIS PAIS { get; set; }
        public virtual TIPO_DIRECCION TIPO_DIRECCION { get; set; }
        public virtual INDIVIDUO INDIVIDUO { get; set; }
    }
}
