//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_MAIL
    {
        public int E_MAIL_ID { get; set; }
        public Nullable<int> INDIVIDUO_ID { get; set; }
        public Nullable<int> TIPO_CORREO_ELECTRONICO_ID { get; set; }
        public string DIRECCION_CORREO_ELECTRONICO { get; set; }
    
        public virtual INDIVIDUO INDIVIDUO { get; set; }
        public virtual TIPO_CORREO_ELECTRONICO TIPO_CORREO_ELECTRONICO { get; set; }
    }
}
