//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTREGA_ORDEN_TRABAJO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTREGA_ORDEN_TRABAJO()
        {
            this.DETALLE_ENTREGA_ORDEN_TRABAJO = new HashSet<DETALLE_ENTREGA_ORDEN_TRABAJO>();
        }
    
        public int ENTREGA_ORDEN_TRABAJO_ID { get; set; }
        public Nullable<long> ORDEN_TRABAJO_ID { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
        public Nullable<int> USUARIO_ENTREGA_ID { get; set; }
        public Nullable<int> USUARIO_RECIBE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ENTREGA_ORDEN_TRABAJO> DETALLE_ENTREGA_ORDEN_TRABAJO { get; set; }
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
    }
}
