//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_REGLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HISTORIAL_REGLA()
        {
            this.ORDEN_TRABAJO_DESCUENTO = new HashSet<ORDEN_TRABAJO_DESCUENTO>();
        }
    
        public long HISTORIAL_REGLA_ID { get; set; }
        public Nullable<long> ORDEN_TRABAJO_ID { get; set; }
        public Nullable<int> ACCION_REGLA_ID { get; set; }
        public Nullable<System.DateTime> FECHA_EJECUCION { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
    
        public virtual ACCION_REGLA ACCION_REGLA { get; set; }
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_TRABAJO_DESCUENTO> ORDEN_TRABAJO_DESCUENTO { get; set; }
    }
}
