//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDIVIDUO_BANCO
    {
        public int PERSONA_BANCO_ID { get; set; }
        public Nullable<int> INDIVIDUO_ID { get; set; }
        public Nullable<int> TIPO_CUENTA_BANCARIA_ID { get; set; }
        public Nullable<int> BANCO_ID { get; set; }
        public string NUMERO_CUENTA { get; set; }
        public Nullable<bool> ES_PRINCIPAL { get; set; }
        public Nullable<bool> ES_PROPIA { get; set; }
    
        public virtual INDIVIDUO INDIVIDUO { get; set; }
        public virtual TIPO_CUENTA_BANCARIA TIPO_CUENTA_BANCARIA { get; set; }
    }
}
