//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUMERACION_ORDEN
    {
        public int NUMERACION_ORDEN_ID { get; set; }
        public Nullable<int> TIPO_LAVADO_ID { get; set; }
        public Nullable<int> SUCURSAL_ID { get; set; }
        public Nullable<int> PUNTO_VENTA_ID { get; set; }
        public string NUMERO_ORDEN { get; set; }
        public Nullable<int> NUMERO { get; set; }
    
        public virtual TIPO_LAVADO TIPO_LAVADO { get; set; }
    }
}
