//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_TRABAJO_COMISION
    {
        public long ORDEN_TRABAJO_COMISION_ID { get; set; }
        public Nullable<long> ORDEN_TRABAJO_ID { get; set; }
        public Nullable<int> VENTA_COMISION_ID { get; set; }
        public Nullable<System.DateTime> FECHA_GENERACION_COMISION { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public Nullable<decimal> VALOR { get; set; }
    
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
        public virtual VENTA_COMISION VENTA_COMISION { get; set; }
    }
}
