//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_TRABAJO_DESCUENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_TRABAJO_DESCUENTO()
        {
            this.APROBACION_DESCUENTO = new HashSet<APROBACION_DESCUENTO>();
        }
    
        public long ORDEN_TRABAJO_DESCUENTO_ID { get; set; }
        public Nullable<long> ORDEN_TRABAJO_ID { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<decimal> PORCENTAJE_FRANQUICIA { get; set; }
        public Nullable<decimal> PORDENTAJE_MATRIZ { get; set; }
        public Nullable<bool> ESTADO_PROCESO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
        public Nullable<int> USUARIO_CREACION_ID { get; set; }
        public Nullable<int> USUARIO_MODIFICACION_ID { get; set; }
        public Nullable<long> HISTORIAL_REGLA_ID { get; set; }
        public string MOTIVO_DESCUENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APROBACION_DESCUENTO> APROBACION_DESCUENTO { get; set; }
        public virtual ORDEN_TRABAJO ORDEN_TRABAJO { get; set; }
    }
}
