//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORCENTAJE_IMPUESTO_SUCURSAL
    {
        public int PORCENTAJE_IMPUESTO_SUCURSAL_ID { get; set; }
        public Nullable<int> PORCENTAJE_IMPUESTO_ID { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
        public Nullable<decimal> BASE_MINIMA { get; set; }
        public Nullable<decimal> BASE_MAXIMA { get; set; }
        public Nullable<int> SUCURSAL_ID { get; set; }
    
        public virtual PORCENTAJE_IMPUESTO PORCENTAJE_IMPUESTO { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
