//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESO
    {
        public long PROCESO_ID { get; set; }
        public Nullable<int> ETAPA_PROCESO_ID { get; set; }
        public Nullable<int> SUCURSAL_ID { get; set; }
        public Nullable<int> PUNTO_VENTA_ID { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO { get; set; }
        public string NUMERO_ORDEN { get; set; }
        public Nullable<bool> SE_ENVIO { get; set; }
        public string MENSAJE { get; set; }
    
        public virtual ETAPA_PROCESO ETAPA_PROCESO { get; set; }
    }
}
