//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR_IMPUESTO
    {
        public decimal PROVEEDOR_IMPUESTO_ID { get; set; }
        public Nullable<int> CONDICION_IMPUESTO_ID { get; set; }
        public Nullable<int> GRUPO_IMPUESTO_ID { get; set; }
        public Nullable<int> IMPUESTO_ID { get; set; }
        public Nullable<int> PORCENTAJE_IMPUESTO_ID { get; set; }
        public Nullable<int> PROVEEDOR_ID { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual GRUPO_IMPUESTO GRUPO_IMPUESTO { get; set; }
        public virtual IMPUESTO IMPUESTO { get; set; }
        public virtual CONDICION_IMPUESTO CONDICION_IMPUESTO { get; set; }
        public virtual PORCENTAJE_IMPUESTO PORCENTAJE_IMPUESTO { get; set; }
    }
}
