//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PREGUNTA_SEGURIDAD
    {
        public int USUARIO_PREGUNTA_SEGURIDAD_ID { get; set; }
        public Nullable<int> PREGUNTA_SEGURIDAD_ID { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public string VALOR_PREGUNTA { get; set; }
    
        public virtual PREGUNTA_SEGURIDAD PREGUNTA_SEGURIDAD { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
