//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.CONTROL_USUARIO = new HashSet<CONTROL_USUARIO>();
            this.HISTORIAL_USUARIO = new HashSet<HISTORIAL_USUARIO>();
            this.USUARIO_PERFIL = new HashSet<USUARIO_PERFIL>();
            this.USUARIO_PREGUNTA_SEGURIDAD = new HashSet<USUARIO_PREGUNTA_SEGURIDAD>();
        }
    
        public int USUARIO_ID { get; set; }
        public Nullable<int> SUCURSAL_ID { get; set; }
        public Nullable<int> PUNTO_VENTA_ID { get; set; }
        public Nullable<int> INDIVIDUO_ID { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CLAVE_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<int> DIAS_VIGENCIA { get; set; }
        public Nullable<bool> HABILITADO { get; set; }
        public Nullable<bool> HABILITADO_SEGURIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_USUARIO> CONTROL_USUARIO { get; set; }
        public virtual INDIVIDUO INDIVIDUO { get; set; }
        public virtual PUNTO_VENTA PUNTO_VENTA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_USUARIO> HISTORIAL_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PREGUNTA_SEGURIDAD> USUARIO_PREGUNTA_SEGURIDAD { get; set; }
        public virtual USUARIO_SEGURIDAD USUARIO_SEGURIDAD { get; set; }
    }
}
