//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_SEGURIDAD
    {
        public int USUARIO_ID { get; set; }
        public string IP { get; set; }
        public Nullable<bool> HABILITADO { get; set; }
        public string NOMBRE_IP { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
