//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_COMISION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTA_COMISION()
        {
            this.ORDEN_TRABAJO_COMISION = new HashSet<ORDEN_TRABAJO_COMISION>();
        }
    
        public int VENTA_COMISION_ID { get; set; }
        public Nullable<int> VENDEDOR_ID { get; set; }
        public Nullable<System.DateTime> FECHA_COMISION { get; set; }
        public Nullable<bool> ESTA_HABILITADO { get; set; }
        public Nullable<decimal> PORCENTAJE_COMISION { get; set; }
        public Nullable<int> SUCURSAL_ID { get; set; }
        public Nullable<int> PUNTO_VENTA_ID { get; set; }
        public Nullable<bool> VIENE_REGLA { get; set; }
        public Nullable<int> TIPO_LAVADO_ID { get; set; }
        public Nullable<int> PROMOCION_APLICADA { get; set; }
    
        public virtual VENDEDOR VENDEDOR { get; set; }
        public virtual TIPO_LAVADO TIPO_LAVADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_TRABAJO_COMISION> ORDEN_TRABAJO_COMISION { get; set; }
    }
}
