//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_COMISION_INDUSTRIALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTA_COMISION_INDUSTRIALES()
        {
            this.DETALLE_VENTA_COMISION_INDUSTRIALES = new HashSet<DETALLE_VENTA_COMISION_INDUSTRIALES>();
        }
    
        public int VENTA_COMISION_INDUSTRIALES_ID { get; set; }
        public Nullable<int> VENDEDOR_ID { get; set; }
        public Nullable<System.DateTime> FECHA_COMISION { get; set; }
        public Nullable<int> SUCURSAL_ID { get; set; }
        public Nullable<int> PUNTO_VENTA_ID { get; set; }
    
        public virtual VENDEDOR VENDEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTA_COMISION_INDUSTRIALES> DETALLE_VENTA_COMISION_INDUSTRIALES { get; set; }
    }
}
