//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLLR.Core.Base.Proveedor.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VISITA()
        {
            this.AGENDA_VISITA = new HashSet<AGENDA_VISITA>();
        }
    
        public int VISITA_ID { get; set; }
        public Nullable<int> ZONA_ID { get; set; }
        public Nullable<int> RUTA_ID { get; set; }
        public Nullable<bool> VISITA_LUNES { get; set; }
        public Nullable<bool> VISITA_MARTES { get; set; }
        public Nullable<bool> VISITA_MIERCOLES { get; set; }
        public Nullable<bool> VISITA_JUEVES { get; set; }
        public Nullable<bool> VISITA_VIERNES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENDA_VISITA> AGENDA_VISITA { get; set; }
        public virtual RUTA RUTA { get; set; }
        public virtual ZONA ZONA { get; set; }
    }
}
